services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: tblog-postgres-dev
    environment:
      POSTGRES_DB: tblog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tblog"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data: 